### ISSUE TITLE
Fussnoten

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.thesis#1]
@signalwerk 
Als Benutzer von diesem Template, möchte ich mit Fussnoten arbeiten können. 
Zusätzlich müssen diese im Beispiel abgebildet werden.

**Comment by signalwerk** [comment]
Unter https://github.com/logrinto/IAD2017.thesis/blob/master/sites/example/src/pages/-example/index.md ist nun das Beispiel drin. 

Hier Fussnoten [hier](https://thesis.logrinto.ch/posts/2020/example/#fussnoten)

Bitte wieder öffnen, wenn du noch etwas brauchst.
