### ISSUE TITLE
Quellen-/Literatur-/Inhalts-/Abbildungsverzeichnis

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.thesis#2]
@signalwerk 
Als Autor möchte ich im Musterordner ein jeweils ein Beispiel  für Quellen-/Literatur-/Inhalts-/Abbildungsverzeichnis sehen.

**Comment by signalwerk** [comment]
Unter https://github.com/logrinto/IAD2017.thesis/blob/master/sites/example/src/pages/-example/index.md ist nun das Beispiel drin. 

* Fussnoten/Quellen [hier](https://thesis.logrinto.ch/posts/2020/example/#fussnoten)
* Fussnoten/Abbildungsverzeichnis [hier](https://thesis.logrinto.ch/posts/2020/example/#abbildungsverzeichnis)
* Inhaltsverzeichnis [hier](https://thesis.logrinto.ch/posts/2020/example/#inhaltsverzeichnis-element)

Bitte wieder öffnen, wenn du noch etwas brauchst.
