### ISSUE TITLE
Zitate

### ISSUE THREAD

**Issue by NMA93** [logrinto/IAD2017.thesis#3]
@signalwerk 
Als Autor möchte ich im Musterordner ein Beispiel sehen wie im Text Zitate oder ganze Textpassagen welche zitiert werden, dargestellt werden.

**Comment by signalwerk** [comment]
Unter https://github.com/logrinto/IAD2017.thesis/blob/master/sites/example/src/pages/-example/index.md ist nun das Beispiel drin. 

Die Darstellung findest du [hier](https://thesis.logrinto.ch/posts/2020/example/#zitate) für die Fussnoten [hier](https://thesis.logrinto.ch/posts/2020/example/#fussnoten)

Bitte wieder öffnen, wenn du noch etwas brauchst.
